environment:

  matrix:
  - PYTHON: "C:\\Python36"
  - PYTHON: "C:\\Python36-x64"

install:
  - "%PYTHON%\\python.exe -m pip install -e .[develop]"

build: off

test_script:
  - "%PYTHON%\\python.exe setup.py nosetests"
